### ISSUE TITLE
libopenmpt development package not found

### ISSUE THREAD

**Issue by diamond-lizard** [realnc/hugor#3]
When I run "qmake" to try to build hugor from source, I get:
```
Info: creating stash file /home/me/compilation/games/if/interpreters/hugor/.qmake.stash
Project ERROR: libopenmpt development package not found
```

There's no mention of libopenmpt being a dependency in the README.  Is this an absolute requirement?  I neither need nor want sound.

**Comment by diamond-lizard** [comment]
It looks like `qmake CONFIG+=disable-audio` allowed qmake to succeed.

**Comment by realnc** [comment]
`qmake -config disable-audio` is needed for now if you don't want to install libopenmpt (it's easy to install though, as it has no dependencies worth mentioning.)

I'm currently working on a new release, and still need to add toggles for the available backends for the MOD music format. libopenmpt is the best choice, but I'll add config options to choose modplug or XMP instead, as those are older and thus more likely to be available in most Linux distros.

**Comment by realnc** [comment]
The MOD music backend is now configurable at build time and the README has been updated. The default is libopenmpt, with libxmp and libmodplug being available alternatives:

    qmake -config xmp

or:

    qmake -config modplug

Commit: 59c4b8b1cf72a9c61a071d1db80506cb46ff0371
