### ISSUE TITLE
[Ubuntu 16.04] If game is open in fullscreen width is wrong

### ISSUE THREAD

**Issue by cibersheep** [realnc/hugor#4]
- Open AppImage
- Open game for example [distree](https://ifdb.tads.org/viewgame?id=5iz05cexg449vrx3) or [Guilty...](https://ifdb.tads.org/viewgame?id=g02gj35cieg77y62)
- Start fullscreen or go fullscreen

Expected: text to be as wide as screen
Behaviour: text is narrow 
Workaround: Play in windowed mode

OS: Ubuntu Studio 16.04
DE: Unity 7

Fullscreen:

![imatge](https://user-images.githubusercontent.com/6640041/55352527-57cd3b80-54c1-11e9-8a1a-eb7eb4d96a45.png)

Fullscreen to windowed mode:

![imatge](https://user-images.githubusercontent.com/6640041/55352553-6e739280-54c1-11e9-8d3b-f04e6219c399.png)

**Comment by realnc** [comment]
This is an artifact of an old 1.x setting. By default, the game window width in fullscreen mode is limited to prevent extremely long lines of text. It is stored as a percentage. However, the old version of Hugor stored it as a pixel value.

To fix this, change the "Fullscreen Width" setting in the preferences, in the "Misc" tab. (Right-click and select "Preferences", you don't have to exit fullscreen.) Does this fix the issue?

I should have accounted for this in 2.0, but I forgot. I'll keep this bug open until I add a proper fix that doesn't require people to manually change the fullscreen width.

**Comment by realnc** [comment]
Fixed by 19f121b0e2d014af350b4393592859ea05b3f6d5. I'll do a 2.1 bugfix release soon.

**Comment by cibersheep** [comment]
Oh, yes. It does... Nice!
Thanks again for your work <3

**Comment by cibersheep** [comment]
Wow. 2.1 works great and native dialogues as well :D
