### ISSUE TITLE
Feature Request: default font overrides in cfg 

### ISSUE THREAD

**Issue by robbsherwin** [realnc/hugor#6]
This is a humble request for the following feature:

- When Hugor open and checks against the appName and appAuthor, if it does not see an entry, it consults the cfg file ... 
- ... for any defaults, as they pertain to the proportional and fixed width font. 
- So something like 

; Default Fixed Font for Windows.
fixedFont = "Terminal,11"   

and 

;Default Proportional Font for Windows.
proportionalFont = "Times New Roman, 15" 

would be great. Thank you!

**Comment by robbsherwin** [comment]
Whoa, this is amazing! I had not seen it before. Thank you so much!

**Comment by realnc** [comment]
All of this is now implemented. I'll put out a 3.0 release shortly.
